pool:
  vmImage: 'windows-latest'

trigger:
  branches:
    include:
      - 'main'

name: $(Build.BuildId)

stages:

  - stage: qa
    displayName: 'Run Automation Test - QA'
    dependsOn: []
    jobs:
      - template: playwright_template.yml
        parameters:
          TEST_USER_PASSWORD: ''
          BASE_URL: ''


  - stage: uat
    displayName: 'Run Automation Test - UAT'
    dependsOn: []
    condition: eq(variables['Build.Reason'], 'Manual')
    jobs:
      - template: playwright_template.yml
        parameters:
          TEST_USER_PASSWORD: ''
          BASE_URL: ''