parameters:
  - name: TEST_USER_PASSWORD
    type: string
  - name: BASE_URL
    type: string

jobs:

  - job: test
    displayName: Run Playwright Tests
    steps:

      - download: none
      
      - checkout: self

      - task: NodeTool@0
        displayName: 'Use Node version 16'
        inputs:
          versionSpec: 16.x

      - script: |
          npm ci
        displayName: "NPM Install"

      - script: |
          npx playwright install --with-deps
        displayName: "Playwright Install"

      - script: |
          set BASE_URL=${{ parameters.BASE_URL }}
          set TEST_ACCOUNT_USERNAME=tbd
          set TEST_ACCOUNT_PASSWORD=tbd
          set CI=true
          set PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml
          npx playwright test
        displayName: "Run Playwright Tests"
        continueOnError: true

      - task: ArchiveFiles@2
        displayName: 'Add playwright-report to Archive'
        inputs:
          rootFolderOrFile: '$(Pipeline.Workspace)/s/playwright-report/'
          archiveFile: '$(Agent.TempDirectory)/$(Build.BuildId)_$(System.JobAttempt)$(System.StageAttempt).zip'

      - task: ArchiveFiles@2
        displayName: 'Add test-results to Archive'
        inputs:
          rootFolderOrFile: '$(Pipeline.Workspace)/s/test-results/'
          archiveFile: '$(Agent.TempDirectory)/$(Build.BuildId)_$(System.JobAttempt)$(System.StageAttempt).zip'
          replaceExistingArchive: false

      - powershell: |
          $folder = '$(Pipeline.Workspace)/s/test-export-files'
          "Test to see if folder [$folder] exists"
          if (Test-Path -Path $folder) {
            echo "##vso[task.setvariable variable=testExportFiles]Yes"
          } else {
            echo "##vso[task.setvariable variable=testExportFiles]No"
          }
        displayName: 'Check for test-export-files Folder'

      - task: ArchiveFiles@2
        displayName: 'Add test-export-files to Archive'
        inputs:
          rootFolderOrFile: '$(Pipeline.Workspace)/s/test-export-files/'
          archiveFile: '$(Agent.TempDirectory)/$(Build.BuildId)_$(System.JobAttempt)$(System.StageAttempt).zip'
          replaceExistingArchive: false
        condition: eq(variables['testExportFiles'], 'Yes')

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifacts'
        inputs:
          targetPath: '$(Agent.TempDirectory)/$(Build.BuildId)_$(System.JobAttempt)$(System.StageAttempt).zip'
          artifact: pipeline-artifacts

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '$(Pipeline.Workspace)/s/results.xml'
          testRunTitle: 'Playwright Testing Demo - $(System.StageName)'
        displayName: 'Publish Test Results'